"""
Generate CRC16-XModem lookup table and save to 'crc_table.py'
Run this once before running the main hunter script.
"""

def generate_table():
    """Generate CRC16-XModem table (polynomial 0x1021)"""
    table = []
    for i in range(256):
        crc = i << 8
        for _ in range(8):
            if crc & 0x8000:
                crc = ((crc << 1) ^ 0x1021) & 0xFFFF
            else:
                crc = (crc << 1) & 0xFFFF
        table.append(crc)
    return table

def write_table_file():
    table = generate_table()
    
    lines = [
        "# Auto-generated by generate_crc_table.py",
        "# Do not edit manually",
        "",
        "CRC16_XMODEM_TABLE = ["
    ]
    
    # Format 8 columns per row for readability
    for i in range(0, 256, 8):
        row_values = ", ".join(f"0x{crc:04x}" for crc in table[i:i+8])
        lines.append(f"    {row_values},")
    
    lines.append("]")
    lines.append("")
    
    filename = "crc_table.py"
    with open(filename, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    
    print(f"✅ Generated {filename} with {len(table)} CRC entries")
    print(f"   Size: ~{len(table) * 2} bytes (lookup table)")

if __name__ == "__main__":
    write_table_file()
